# Generated by Django 5.1.2 on 2024-11-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("image", models.ImageField(upload_to="board/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("SELL", "ПРОДАМ"),
                            ("BUY", "КУПЛЮ"),
                            ("EXCHANGE", "ОБМЕНЯЮ"),
                            ("VARIOUS", "РАЗНОЕ"),
                            ("SERVICES", "УСЛУГИ"),
                        ],
                        max_length=10,
                    ),
                ),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
