# Generated by Django 5.1.2 on 2024-11-10 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumsubsection_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
