# Generated by Django 5.1.2 on 2024-11-10 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forumtopic_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumtopic',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
