# Generated by Django 5.1.2 on 2024-11-19 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_forumtopic_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumsection',
            name='message_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='forumsection',
            name='topic_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
