# Generated by Django 5.1.2 on 2024-11-19 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0005_forumsection_message_count_forumsection_topic_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumsection',
            name='message_count',
        ),
        migrations.RemoveField(
            model_name='forumsection',
            name='topic_count',
        ),
    ]
