# Generated by Django 5.1.2 on 2024-11-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/default_avatar.jpg', upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gametag_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Game Tag ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nintendo_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nintendo ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='psn_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='PSN ID'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='steam_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Steam ID'),
        ),
    ]
