# Generated by Django 5.1.2 on 2024-12-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("links", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="link/"),
        ),
    ]
