# Generated by Django 5.1.2 on 2024-11-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_advertisement_upcominggame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upcominggame',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Текст'),
        ),
    ]
