# Generated by Django 5.1.2 on 2024-11-04 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_upcominggame_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upcominggame',
            options={'verbose_name': 'Ждем и Верим', 'verbose_name_plural': 'Ждем и Верим'},
        ),
        migrations.RemoveField(
            model_name='upcominggame',
            name='text',
        ),
        migrations.AddField(
            model_name='upcominggame',
            name='game_title',
            field=models.CharField(default='title', max_length=40, verbose_name='Название игры'),
            preserve_default=False,
        ),
    ]
